package cl.desagen.chilquinta.sharepoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2019-12-29T19:03:51.645-03:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "SharePointSCSSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SharePointSCSSoap {

    @WebMethod(operationName = "SetDocumento", action = "http://tempuri.org/SetDocumento")
    @RequestWrapper(localName = "SetDocumento", targetNamespace = "http://tempuri.org/", className = "cl.desagen.chilquinta.sharepoint.SetDocumento")
    @ResponseWrapper(localName = "SetDocumentoResponse", targetNamespace = "http://tempuri.org/", className = "cl.desagen.chilquinta.sharepoint.SetDocumentoResponse")
    @WebResult(name = "SetDocumentoResult", targetNamespace = "http://tempuri.org/")
    public cl.desagen.chilquinta.sharepoint.Respuesta setDocumento(
        @WebParam(name = "objDocumento", targetNamespace = "http://tempuri.org/")
        cl.desagen.chilquinta.sharepoint.DocumentoSCS objDocumento
    );
}
